# Generated by Django 3.1.4 on 2021-04-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genero', '0001_initial'),
        ('editora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('nota_media', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('num_paginas', models.IntegerField()),
                ('data_publicacao', models.DateField()),
                ('total_de_notas', models.IntegerField()),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
                ('editora', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='editora.editora')),
                ('genero', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='genero.genero')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitor', to='livros.livro')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('livro_id', 'usuario_id')},
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='leitores',
            field=models.ManyToManyField(through='livros.UsuarioLivro', to=settings.AUTH_USER_MODEL),
        ),
    ]
