# Generated by Django 3.1.4 on 2021-04-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='', null=True, upload_to='livros/capas'),
        ),
    ]
