# Generated by Django 3.1.4 on 2021-03-28 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='leitores',
            field=models.ManyToManyField(through='livros.UsuarioLivro', to=settings.AUTH_USER_MODEL),
        ),
    ]
