# Generated by Django 3.1.4 on 2021-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='', null=True, upload_to='livros/capas/'),
        ),
    ]
