# Generated by Django 3.1.4 on 2021-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=50, unique=True)),
                ('localizacao', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
