# Generated by Django 3.1.4 on 2021-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='localizacao',
            field=models.CharField(max_length=50),
        ),
    ]
